//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Employee
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [StringLength(25, ErrorMessage = "Name must not have more than 25 chars")]
        [MinLength(3,ErrorMessage ="Name must have at least 3 chars")]
        [Required(ErrorMessage ="Name is Required")]
        public string Name { get; set; }
        [Range(10000, 100000, ErrorMessage ="Salary must be between 10000 and 100000")]
        public int Salary { get; set; }
    }
}
